apiVersion: v1
kind: Service
metadata:
  name: jenkins
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.7
  ports:
    - port: 8080
  selector:
    app: jenkins
